### ISSUE TITLE
Bump cloud-formation template version to 1.0.6

### ISSUE THREAD

**Issue by karthikmuralidharan** [scalyr/scalyr-aws-serverless#11]
We are waiting to make use of https://github.com/scalyr/scalyr-aws-serverless/pull/10. Is it possbile to bump the cloud formation version with the updated code for the lambda ?

**Comment by ajtcode** [comment]
@karthikmuralidharan you can access this now via https://console.aws.amazon.com/cloudformation/home?#stacks/create/review?stackName=ScalyrCloudWatchLogsImporter&templateURL=https://scalyr-aws-serverless.s3.amazonaws.com/cloudwatch_logs/cloudwatch-logs-1.0.6.yml 

Hope this helps!
